system:
  configVersion: 3
  debug: false
  language: 'en'
  updateNotifications: true
  useBukkitTimer: true
storage:
  type: 'flatfile' #can be flatfile, sqlite, or mysql
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    prefix: 'j3_'
jailing:
  during:
    blockBreakPenalty: 5m
    blockBreakProtection: true
    blockBreakWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be broken at any time by prisoners
    blockPlacePenalty: 5m
    blockPlaceProtection: true
    blockPlaceWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be placed at any time by prisoners
    commandPenalty: 5m
    commandProtection: true
    commandWhitelist: ['/ping', '/list', '/jail status']
    countDownTimeWhileOffline: false
    cropTramplingPenalty: 5m
    cropTramplingProtection: true
    foodControl: true
    foodControlMax: 20
    foodControlMin: 10
    ignoreSleeping: true
    maxAFKTime: 10m #in minutes
    movePenalty: 10m
    moveProtection: true
    openChest: true
    preventInteractionBlocks: ['wooden_door', 'iron_door_block']
    preventInteractionBlocksPenalty: 5m
    preventInteractionItems: []
    preventInteractionItemsPenalty: 5m
    recieveMessages: true
  jail:
    automaticMute: true
    broadcastJailing: false
    commands: []
    defaultJail: nearest #the jail nearest to the player
    defaultTime: 30m #default the time to 30 minutes, if no time
    deleteInventory: false
    gameMode: adventure
    logToConsole: true
    logToProfile: false
    storeInventory: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true
    database: 'jailDatabase'
jails:
  endermenProtection: true
  explosionProtection: true
jailstick: ["stick,30,,Running away"]