system:
  configVersion: 3
  debug: false
  language: 'en'
  updateNotifications: true
storage:
  type: 'flatfile' #can be flatfile, sqlite, or mysql
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
jailing:
  during:
    countDownTimeWhileOffline: false
    ignoreSleeping: true
    openChest: true
  jail:
    automaticMute: true
    broadcastJailing: false
    commands: []
    defaultJail: nearest #the jail nearest to the player
    defaultTime: 30m #default the time to 30 minutes, if no time
    deleteInventory: false
    gameMode: adventure
    logToConsole: true
    logToProfile: false
    storeInventory: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true