system:
  configVersion: 3
  debug: false
  language: 'en'
  updateNotifications: true
  useBukkitTimer: true
storage:
  type: 'flatfile' #can be flatfile, sqlite, or mysql
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    database: 'jailDatabase'
    prefix: 'j3_'
jailing:
  during:
    blockBreakPenalty: 5m
    blockBreakProtection: true
    blockBreakWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be broken at any time by prisoners
    blockPlacePenalty: 5m
    blockPlaceProtection: true
    blockPlaceWhiteList: ['crops', 'carrot', 'potato'] # these blocks can be placed at any time by prisoners
    commandPenalty: 5m
    commandProtection: true
    commandWhitelist: ['/ping', '/list', '/jail status', '/jail pay']
    countDownTimeWhileOffline: false
    cropTramplingPenalty: 5m
    cropTramplingProtection: true
    foodControl: true
    foodControlMax: 20
    foodControlMin: 10
    ignoreSleeping: true
    maxAFKTime: 10m #in minutes
    movePenalty: 10m
    moveProtection: true
    openChest: true
    preventInteractionBlocks: ['wooden_door', 'iron_door_block']
    preventInteractionBlocksPenalty: 5m
    preventInteractionItems: []
    preventInteractionItemsPenalty: 5m
    recieveMessages: true
    scoreboard:
      enabled: false
      title: 'Jail Info'
      time: '&aTime:'
  jail:
    automaticMute: true
    broadcastJailing: false
    clothing:
      enabled: true
      helmet: leather_boots~255,102,0
      chest: leather_chestplate~255,102,0
      legs: leather_leggings~255,102,0
      boots: leather_boots~255,102,0
    commands: []
    defaultJail: nearest #the jail nearest to the player
    defaultTime: 30m #default the time to 30 minutes, if no time
    deleteInventory: false
    gameMode: adventure
    logToConsole: true
    logToProfile: false
    storeInventory: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true
jails:
  endermenProtection: true
  explosionProtection: true
jailpay:
  enabled: true
  item: air
  pricePerMinute: 1.5
  priceInfinite: 10000
jailstick:
  enabled: true
  sticks: ["stick,30,,Running away"]